var express = require('express');
var router = express.Router();
const adminCotnroller=require('../Controllers/AdminController');
router.post('/admin/addHotline',adminCotnroller.PostAddHotline);
router.post('/admin/addAdmin',adminCotnroller.PostAddAdmin);
router.get('/admin/AllOrganizations',adminCotnroller.getAllOrganizationsInfo);
router.get('/admin/AllPendingOrganizations',adminCotnroller.ViewAllPendings);
router.post('/admin/handleRequest',adminCotnroller.ApproveOrganization);
router.delete('/admin/removeOrganization',adminCotnroller.RemoveOrganization);
module.exports=router;